name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.10.5 ]
        poetry-version: [ 1.1.14 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.14
      - name: Install packages
        run: poetry install
      - name: Lint and flake8
        working-directory: yoloraft/
        run: |
          poetry install
          poetry run black . --check
          poetry run flake8 --config ../setup.cfg

  run_tests:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.10.5 ]
        poetry-version: [ 1.1.14 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.14
      - name: Install packages
        run: poetry install
      - name: Run tests
        run: >
          poetry run pytest
          --cov-config=.coveragerc
          --cov=app
          --cov-report html:cov_html
          --cov-report xml:coverage.xml
